### ISSUE TITLE
2.4.1 does not work with IE11

### ISSUE THREAD

**Issue by armandfrigo** [ClimberAB/ClimberCustomReport#75]
The extension does not display within **Internet Explorer 11** (IE 11.611.16299.0)
Climber Report extension **2.4.1**
Qlik Sense Server **June 2018 SP1**

The console log returns: (I removed our server name)

DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
analysis
HTML1300: Navigation occurred.
analysis
**TypeError: Object doesn't support property or method 'includes'
   at Anonymous function (https://ServerName/extensions/cl-custom-report/cl-custom-report.js:1:31214)
   at p (https://ServerName/resources/assets/client/client.c2fc1f6d5055907acb21.js:42:29779)
   at t (https://ServerName/resources/assets/client/client.c2fc1f6d5055907acb21.js:42:60927)
   at Anonymous function (https://ServerName/resources/chunks/qvangular.79d90a74b535aba6bdb9.js:7:38579)
   at p.prototype.$digest (https://ServerName/resources/assets/client/client.c2fc1f6d5055907acb21.js:42:117539)
   at p.prototype.$apply (https://ServerName/resources/assets/client/client.c2fc1f6d5055907acb21.js:42:119053)
   at Anonymous function (https://ServerName/resources/assets/client/client.c2fc1f6d5055907acb21.js:42:127220)
   at d (https://ServerName/resources/assets/client/client.c2fc1f6d5055907acb21.js:42:36169)
   at Anonymous function (https://ServerName/resou**

**Chrome**
![climber_report_chrome](https://user-images.githubusercontent.com/9445066/46220020-3a1fed80-c349-11e8-903b-03ce98fb3bc6.jpg)

**IE11**
![climber_report_ie11](https://user-images.githubusercontent.com/9445066/46220021-3a1fed80-c349-11e8-855e-3ac9315c06cd.jpg)

**Comment by kfsjostrand** [comment]
This issue is Fixed in 2.4.2 
Download the latest version here
https://github.com/ClimberAB/ClimberCustomReport/releases/tag/v2.4.2

**Comment by armandfrigo** [comment]
Hi Karl, 
Which I did immediately and could deploy successfully on IE.
A belated thank you for your swift actions and impressively fast reaction!
Kind regards,
Armand
